import { SPRING, SUMMER, FALL, WINTER } from "./calendar";
import { Crop } from "./model";

export const crops: Crop[] = [
  {
    name: "Rice Shoot",
    maturityTimeDays: 8,
    seasons: [SPRING],
    seedPrice: 20,
    sellPrice: 30,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 10,
      chanceForExtraCrops: 0.1,
    },
  },
  {
    name: "Amaranth Seeds",
    maturityTimeDays: 7,
    seasons: [FALL],
    seedPrice: 35,
    sellPrice: 150,
  },
  {
    name: "Grape Starter",
    maturityTimeDays: 10,
    seasons: [FALL],
    seedPrice: 30,
    sellPrice: 80,
  },
  {
    name: "Hops Starter",
    maturityTimeDays: 11,
    seasons: [SUMMER],
    seedPrice: 30,
    sellPrice: 25,
  },
  {
    name: "Rare Seed",
    maturityTimeDays: 24,
    seasons: [FALL],
    seedPrice: 200,
    sellPrice: 3000,
  },
  {
    name: "Fairy Seeds",
    maturityTimeDays: 12,
    seasons: [FALL],
    seedPrice: 100,
    sellPrice: 290,
  },
  {
    name: "Tulip Bulb",
    maturityTimeDays: 6,
    seasons: [SPRING],
    seedPrice: 10,
    sellPrice: 30,
  },
  {
    name: "Jazz Seeds",
    maturityTimeDays: 7,
    seasons: [SPRING],
    seedPrice: 15,
    sellPrice: 50,
  },
  {
    name: "Sunflower Seeds",
    maturityTimeDays: 8,
    seasons: [SUMMER, FALL],
    seedPrice: 20,
    sellPrice: 80,
  },
  {
    name: "Coffee Bean",
    maturityTimeDays: 10,
    seasons: [SPRING, SUMMER],
    seedPrice: 15,
    sellPrice: 15,
    extraHarvestChance: {
      minHarvest: 4,
      maxHarvest: 4,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
  },
  {
    name: "Poppy Seeds",
    maturityTimeDays: 7,
    seasons: [SUMMER],
    seedPrice: 50,
    sellPrice: 140,
  },
  {
    name: "Spangle Seeds",
    maturityTimeDays: 8,
    seasons: [SUMMER],
    seedPrice: 25,
    sellPrice: 90,
  },
  {
    name: "Parsnip Seeds",
    maturityTimeDays: 4,
    seasons: [SPRING],
    seedPrice: 10,
    sellPrice: 35,
  },
  {
    name: "Bean Starter",
    maturityTimeDays: 10,
    seasons: [SPRING],
    seedPrice: 30,
    sellPrice: 40,
  },
  {
    name: "Cauliflower Seeds",
    maturityTimeDays: 12,
    seasons: [SPRING],
    seedPrice: 40,
    sellPrice: 175,
  },
  {
    name: "Potato Seeds",
    maturityTimeDays: 6,
    seasons: [SPRING],
    seedPrice: 25,
    sellPrice: 80,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.2,
    },
  },
  {
    name: "Garlic Seeds",
    maturityTimeDays: 4,
    seasons: [SPRING],
    seedPrice: 20,
    sellPrice: 60,
  },
  {
    name: "Kale Seeds",
    maturityTimeDays: 6,
    seasons: [SPRING],
    seedPrice: 35,
    sellPrice: 110,
  },
  {
    name: "Rhubarb Seeds",
    maturityTimeDays: 13,
    seasons: [SPRING],
    seedPrice: 50,
    sellPrice: 220,
  },
  {
    name: "Melon Seeds",
    maturityTimeDays: 12,
    seasons: [SUMMER],
    seedPrice: 40,
    sellPrice: 250,
  },
  {
    name: "Tomato Seeds",
    maturityTimeDays: 11,
    seasons: [SUMMER],
    seedPrice: 25,
    sellPrice: 60,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.05,
    },
  },
  {
    name: "Blueberry Seeds",
    maturityTimeDays: 13,
    seasons: [SUMMER],
    seedPrice: 40,
    sellPrice: 50,
    extraHarvestChance: {
      minHarvest: 3,
      maxHarvest: 3,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
  },
  {
    name: "Pepper Seeds",
    maturityTimeDays: 5,
    seasons: [SUMMER],
    seedPrice: 20,
    sellPrice: 40,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.03,
    },
  },
  {
    name: "Wheat Seeds",
    maturityTimeDays: 4,
    seasons: [SUMMER, FALL],
    seedPrice: 5,
    sellPrice: 25,
  },
  {
    name: "Radish Seeds",
    maturityTimeDays: 6,
    seasons: [SUMMER],
    seedPrice: 20,
    sellPrice: 90,
  },
  {
    name: "Red Cabbage Seeds",
    maturityTimeDays: 9,
    seasons: [SUMMER],
    seedPrice: 50,
    sellPrice: 260,
  },
  {
    name: "Starfruit Seeds",
    maturityTimeDays: 13,
    seasons: [SUMMER],
    seedPrice: 200,
    sellPrice: 750,
  },
  {
    name: "Corn Seeds",
    maturityTimeDays: 14,
    seasons: [SUMMER, FALL],
    seedPrice: 75,
    sellPrice: 50,
  },
  {
    name: "Eggplant Seeds",
    maturityTimeDays: 5,
    seasons: [FALL],
    seedPrice: 10,
    sellPrice: 60,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.002,
    },
  },
  {
    name: "Artichoke Seeds",
    maturityTimeDays: 8,
    seasons: [FALL],
    seedPrice: 15,
    sellPrice: 160,
  },
  {
    name: "Pumpkin Seeds",
    maturityTimeDays: 13,
    seasons: [FALL],
    seedPrice: 50,
    sellPrice: 320,
  },
  {
    name: "Bok Choy Seeds",
    maturityTimeDays: 4,
    seasons: [FALL],
    seedPrice: 25,
    sellPrice: 80,
  },
  {
    name: "Yam Seeds",
    maturityTimeDays: 10,
    seasons: [FALL],
    seedPrice: 30,
    sellPrice: 160,
  },
  {
    name: "Cranberry Seeds",
    maturityTimeDays: 7,
    seasons: [FALL],
    seedPrice: 120,
    sellPrice: 75,
    extraHarvestChance: {
      minHarvest: 2,
      maxHarvest: 2,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.1,
    },
  },
  {
    name: "Beet Seeds",
    maturityTimeDays: 6,
    seasons: [FALL],
    seedPrice: 10,
    sellPrice: 100,
  },
  {
    name: "Spring Seeds",
    maturityTimeDays: 7,
    seasons: [SPRING],
    seedPrice: 35,
    sellPrice: 50,
  },
  {
    name: "Summer Seeds",
    maturityTimeDays: 7,
    seasons: [SUMMER],
    seedPrice: 55,
    sellPrice: 80,
  },
  {
    name: "Fall Seeds",
    maturityTimeDays: 7,
    seasons: [FALL],
    seedPrice: 45,
    sellPrice: 40,
  },
  {
    name: "Winter Seeds",
    maturityTimeDays: 7,
    seasons: [WINTER],
    seedPrice: 30,
    sellPrice: 70,
  },
  {
    name: "Ancient Seeds",
    maturityTimeDays: 28,
    seasons: [SPRING, SUMMER, FALL],
    seedPrice: 30,
    sellPrice: 550,
  },
  {
    name: "Strawberry Seeds",
    maturityTimeDays: 8,
    seasons: [SPRING],
    seedPrice: 0,
    sellPrice: 120,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
  },
  {
    name: "Cactus Seeds",
    maturityTimeDays: 12,
    seasons: [SPRING, SUMMER, FALL, WINTER],
    seedPrice: 0,
    sellPrice: 75,
  },
  {
    name: "Taro Tuber",
    maturityTimeDays: 10,
    seasons: [SUMMER],
    seedPrice: 20,
    sellPrice: 100,
  },
  {
    name: "Pineapple Seeds",
    maturityTimeDays: 14,
    seasons: [SUMMER],
    seedPrice: 240,
    sellPrice: 300,
  },
  {
    name: "Fiber Seeds",
    maturityTimeDays: 7,
    seasons: [SPRING, SUMMER, FALL, WINTER],
    seedPrice: 5,
    sellPrice: 1,
    extraHarvestChance: {
      minHarvest: 4,
      maxHarvest: 7,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.01,
    },
  },
  {
    name: "Qi Bean",
    maturityTimeDays: 4,
    seasons: [SPRING, SUMMER, FALL, WINTER],
    seedPrice: 1,
    sellPrice: 1,
  },
];
