import { SPRING, SUMMER, FALL, WINTER } from "./calendar";
import { Crop, Source } from "./model";

export const crops: Crop[] = [
  {
    name: "Rice Shoot",
    maturityTimeDays: 8, // Account for irrigation; it's only 6 if it's irrigated...
    seasons: [SPRING],
    sellPrice: 30,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 10,
      chanceForExtraCrops: 0.1,
    },
    sources: [Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 40,
      [Source.TRAVELLING_CART]: 450,
    },
  },
  {
    name: "Amaranth Seeds",
    maturityTimeDays: 7,
    seasons: [FALL],
    sellPrice: 150,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 70,
      [Source.JOJAMART]: 87,
      [Source.TRAVELLING_CART]: 602.5,
    },
  },
  {
    name: "Grape Starter",
    maturityTimeDays: 10,
    regrowTimeDays: 3,
    seasons: [FALL],
    sellPrice: 80,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 60,
      [Source.JOJAMART]: 75,
      [Source.TRAVELLING_CART]: 600,
    },
  },
  {
    name: "Hops Starter",
    maturityTimeDays: 11,
    regrowTimeDays: 1,
    seasons: [SUMMER],
    sellPrice: 25,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 60,
      [Source.JOJAMART]: 75,
      [Source.TRAVELLING_CART]: 600,
    },
  },
  {
    name: "Rare Seed",
    maturityTimeDays: 24,
    seasons: [FALL],
    sellPrice: 3000,
    sources: [Source.TRAVELLING_CART],
    price: {
      [Source.TRAVELLING_CART]: 1000,
    },
  },
  {
    name: "Fairy Seeds",
    maturityTimeDays: 12,
    seasons: [FALL],
    sellPrice: 290,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 200,
      [Source.JOJAMART]: 250,
      [Source.TRAVELLING_CART]: 650,
    },
  },
  {
    name: "Tulip Bulb",
    maturityTimeDays: 6,
    seasons: [SPRING],
    sellPrice: 30,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 20,
      [Source.JOJAMART]: 25,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Jazz Seeds",
    maturityTimeDays: 7,
    seasons: [SPRING],
    sellPrice: 50,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 30,
      [Source.JOJAMART]: 37,
      [Source.TRAVELLING_CART]: 600,
    },
  },
  {
    name: "Sunflower Seeds",
    maturityTimeDays: 8,
    seasons: [SUMMER, FALL],
    sellPrice: 80, // Seeds also drop 'between 75% and 90% of the time'; they sell for 20g each, but can be used later on. Seeds have not been included in the 'sellPrice' field.
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 200,
      [Source.JOJAMART]: 125,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Coffee Bean",
    maturityTimeDays: 10,
    regrowTimeDays: 2,
    seasons: [SPRING, SUMMER],
    sellPrice: 15, // Coffee Beans are their own seed; therefore the value calculated is wrong.
    extraHarvestChance: {
      minHarvest: 4,
      maxHarvest: 4,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
    sources: [Source.TRAVELLING_CART],
    price: {
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Poppy Seeds",
    maturityTimeDays: 7,
    seasons: [SUMMER],
    sellPrice: 140,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 100,
      [Source.JOJAMART]: 125,
      [Source.TRAVELLING_CART]: 575,
    },
  },
  {
    name: "Spangle Seeds",
    maturityTimeDays: 8,
    seasons: [SUMMER],
    sellPrice: 90,
    sources: [Source.PIERRE, Source.JOJAMART, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 50,
      [Source.JOJAMART]: 62,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Parsnip Seeds",
    maturityTimeDays: 4,
    seasons: [SPRING],
    sellPrice: 35,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 20,
      [Source.JOJAMART]: 25,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Bean Starter",
    maturityTimeDays: 10,
    regrowTimeDays: 3,
    seasons: [SPRING],
    sellPrice: 40,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 60,
      [Source.JOJAMART]: 75,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Cauliflower Seeds",
    maturityTimeDays: 12,
    seasons: [SPRING],
    sellPrice: 175,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 80,
      [Source.JOJAMART]: 100,
      [Source.TRAVELLING_CART]: 560,
    },
  },
  {
    name: "Potato Seeds",
    maturityTimeDays: 6,
    seasons: [SPRING],
    sellPrice: 80,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.2,
    },
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 50,
      [Source.JOJAMART]: 62,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Garlic Seeds",
    maturityTimeDays: 4,
    seasons: [SPRING],
    sellPrice: 60,
    sources: [Source.PIERRE_YEAR2_PLUS, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 40,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Kale Seeds",
    maturityTimeDays: 6,
    seasons: [SPRING],
    sellPrice: 110,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 70,
      [Source.JOJAMART]: 87,
      [Source.TRAVELLING_CART]: 502.5,
    },
  },
  {
    name: "Rhubarb Seeds",
    maturityTimeDays: 13,
    seasons: [SPRING],
    sellPrice: 220,
    sources: [Source.OASIS_SHOP, Source.TRAVELLING_CART],
    price: {
      [Source.OASIS_SHOP]: 100,
      [Source.TRAVELLING_CART]: 575,
    },
  },
  {
    name: "Melon Seeds",
    maturityTimeDays: 12,
    seasons: [SUMMER],
    sellPrice: 250,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 80,
      [Source.JOJAMART]: 100,
      [Source.TRAVELLING_CART]: 560,
    },
  },
  {
    name: "Tomato Seeds",
    maturityTimeDays: 11,
    regrowTimeDays: 4,
    seasons: [SUMMER],
    sellPrice: 60,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.05,
    },
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 50,
      [Source.JOJAMART]: 62,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Blueberry Seeds",
    maturityTimeDays: 13,
    regrowTimeDays: 4,
    seasons: [SUMMER],
    sellPrice: 50,
    extraHarvestChance: {
      minHarvest: 3,
      maxHarvest: 3,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
    sources: [Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 80,
      [Source.TRAVELLING_CART]: 560,
    },
  },
  {
    name: "Pepper Seeds",
    maturityTimeDays: 5,
    regrowTimeDays: 3,
    seasons: [SUMMER],
    sellPrice: 40,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.03,
    },
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 40,
      [Source.JOJAMART]: 50,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Wheat Seeds",
    maturityTimeDays: 4,
    seasons: [SUMMER, FALL],
    sellPrice: 25,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 10,
      [Source.JOJAMART]: 12,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Radish Seeds",
    maturityTimeDays: 6,
    seasons: [SUMMER],
    sellPrice: 90,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 40,
      [Source.JOJAMART]: 50,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Red Cabbage Seeds",
    maturityTimeDays: 9,
    seasons: [SUMMER],
    sellPrice: 260,
    sources: [Source.PIERRE_YEAR2_PLUS, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 100,
      [Source.TRAVELLING_CART]: 575,
    },
  },
  {
    name: "Starfruit Seeds",
    maturityTimeDays: 13,
    seasons: [SUMMER],
    sellPrice: 750,
    sources: [Source.OASIS_SHOP, Source.TRAVELLING_CART],
    price: {
      [Source.OASIS_SHOP]: 400,
      [Source.TRAVELLING_CART]: 800,
    },
  },
  {
    name: "Corn Seeds",
    maturityTimeDays: 14,
    regrowTimeDays: 4,
    seasons: [SUMMER, FALL],
    sellPrice: 50,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 150,
      [Source.JOJAMART]: 187,
      [Source.TRAVELLING_CART]: 612.5,
    },
  },
  {
    name: "Eggplant Seeds",
    maturityTimeDays: 5,
    regrowTimeDays: -5,
    seasons: [FALL],
    sellPrice: 60,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.002,
    },
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 20,
      [Source.JOJAMART]: 25,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Artichoke Seeds",
    maturityTimeDays: 8,
    seasons: [FALL],
    sellPrice: 160,
    sources: [Source.PIERRE_YEAR2_PLUS, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 30,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Pumpkin Seeds",
    maturityTimeDays: 13,
    seasons: [FALL],
    sellPrice: 320,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 100,
      [Source.JOJAMART]: 125,
      [Source.TRAVELLING_CART]: 575,
    },
  },
  {
    name: "Bok Choy Seeds",
    maturityTimeDays: 4,
    seasons: [FALL],
    sellPrice: 80,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 50,
      [Source.JOJAMART]: 62,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Yam Seeds",
    maturityTimeDays: 10,
    seasons: [FALL],
    sellPrice: 160,
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 60,
      [Source.JOJAMART]: 75,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Cranberry Seeds",
    maturityTimeDays: 7,
    regrowTimeDays: 5,
    seasons: [FALL],
    sellPrice: 75,
    extraHarvestChance: {
      minHarvest: 2,
      maxHarvest: 2,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.1,
    },
    sources: [Source.JOJAMART, Source.PIERRE, Source.TRAVELLING_CART],
    price: {
      [Source.PIERRE]: 240,
      [Source.JOJAMART]: 300,
      [Source.TRAVELLING_CART]: 590,
    },
  },
  {
    name: "Beet Seeds",
    maturityTimeDays: 6,
    seasons: [FALL],
    sellPrice: 100,
    sources: [Source.OASIS_SHOP, Source.TRAVELLING_CART],
    price: {
      [Source.OASIS_SHOP]: 20,
      [Source.TRAVELLING_CART]: 550,
    },
  },
  {
    name: "Strawberry Seeds",
    maturityTimeDays: 8,
    regrowTimeDays: 4,
    seasons: [SPRING],
    sellPrice: 120,
    extraHarvestChance: {
      minHarvest: 1,
      maxHarvest: 1,
      maxHarvestIncreasePerFarmingLevel: 0,
      chanceForExtraCrops: 0.02,
    },
    sources: [Source.EGG_FESTIVAL],
    price: {
      [Source.EGG_FESTIVAL]: 100,
    },
  },
  {
    name: "Cactus Seeds",
    maturityTimeDays: 12,
    regrowTimeDays: 3,
    seasons: [],
    sellPrice: 75,
    sources: [Source.OASIS_SHOP],
    price: {
      [Source.OASIS_SHOP]: 150,
    },
  },
];
